---
name: "Prowl"
guid: "e33266b6-4e16-4412-8c2c-a93d65d458e5"
version: "2.0.0.0"
targetAbi: "10.6.0"
owner: "crobibero"
description: "Sends notifications using the Prowl service"
overview: >
    Get notifications via Prowl
category: "Notifications"
artifacts:
  - "Jellyfin.Plugin.Prowl.dll"
changelog: >
  10.6 compatibility
